### ISSUE TITLE
Need better picture for landing page (/home)

### ISSUE THREAD

**Issue by HarryMWinters** [mcphee-winters/mcphee-winters.com#2]
They should be free, simple and ideally somehow related to coding or us.

**Comment by imwinters** [comment]
Creative Commons Image Sources
** CC0 is no-attribution required, commercial/non-commercial allowed, derivatives allowed.
https://ccsearch.creativecommons.org/
https://www.pexels.com/creative-commons-images/
https://unsplash.com/creative-commons-images
https://www.flickr.com/creativecommons/
